default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5

development:
  <<: *default
  username: root
  database: gomagazine_development
  socket: /tmp/mysql.sock

test: &test
  <<: *default
  username: root
  database: gomagazine_test
  socket: /tmp/mysql.sock

cucumber:
  <<: *test
